### ISSUE TITLE
 Can't running

### ISSUE THREAD

**Issue by 562218352** [estebanuri/face_recognition#33]
I'v been run into this error as below,please help me:

Internal error: Cannot create interpreter: Op builtin_code out or range: 101. Are you using old TFLite binary with newer model?Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:52)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)
        at com.zh.lite.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:145)

**Comment by lsCoding666** [comment]
Same problem. Did you soloved it?
